# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Welcome to The Art of Changing... Glen Park, practitioner of Alexander Technique and Chakra Therapy...
email: contact@glenpark.uk
description: >- # this means to ignore newlines until "baseurl:"
  Glen Park is a highly esteemed Alexander Technique and Chakra Therapy practitioner
  and tutor based in West Sussex, UK. Glen Park provides workshops and courses
  and is the author of The Art of Changing and Chakra Healing Therapy
baseurl: "" # the subpath of your site, e.g. /blog
url: # intentionally left blank (Github Pages and Jekyll Serve overwrite this value)
production_url: "https://glenpark.uk" # where the production version of this site is accessed
twitter_username: jekyllrb
github_username:  jekyll
facebook_username: "glenpark.alexanderteacher"
google_tag_manager: GTM-TP6H8BZ
keywords: Glen Park, The Art of Changing, Chakra Therapy, Chakra Healing Therapy, Alexander Technique, books, courses, CDs, workshops
author: Glen Park
# Default slides for header slider in case of fallback
header_slider:
- quote: "&hellip; every single thing we are doing in the work is exactly what is being done in Nature&hellip; the difference being that we are learning to do it consciously"
  credit: FM Alexander
  img: bg14.jpg
  credit_class: quotecreditwhite
- quote: Because things are the way they are,<br />things will not stay the way they are
  credit: Berthold Brecht
  img: bg1.jpg
  credit_class: quotecreditblack
- quote: People do not decide their futures, they decide their habits and their habits decide their futures
  credit: FM Alexander
  img: bg2.jpg
  credit_class: quotecreditblack
# Header navigation
navigation_header: 
 - label: Welcome
   id: home
   sub_menu: 
 - label: Individual<br>& Group Work
   id: work
   sub_menu:
      - label: Individual Sessions
        id: sessions
      - label: Workshops & Courses
        id: workshops
 - label: Books & CD's
   id: books
   sub_menu:
      - label: The Art of Changing CD
        id: theartofchangingcd
      - label: The Art of Changing
        id: theartofchanging
      - label: Peggy Williams Pamphlet
        id: peggywilliams
      - label: Chakra Healing Therapy
        id: touchingthesoul
 - label: Testimonials
   id: testimonials
   sub_menu:
 - label: Contact Glen
   id: contact
   sub_menu:
# Unnsupported meta tags
# designer: Ian Forster,Graphic Alchemy
# copyright: Glen Park 2018 
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - source
   - gulpfile.js
   - package.json
   - package-lock.json
   - git_submodules
   - README.md
   - CNAME
   - vendor